### ISSUE TITLE
missing dataset configs

### ISSUE THREAD

**Issue by fcakyon** [KostadinovShalon/UAVDetectionTrackingBenchmark#1]
Hello, thanks a lot for this comprehensive benchmark repo. Im a PhD student and want to use this repo to pursue my research. 

[In this training config](https://github.com/KostadinovShalon/UAVDetectionTrackingBenchmark/blob/main/detection/configs/drone-vs-bird/faster_rcnn_r50_fpn_2x_drone-vs-bird.py), it seems that your are using the default `coco_detection.py` dataset config file. It uses [CocoDataset](https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/configs/_base_/datasets/coco_detection.py#L1) as the dataset type. However that dataset type [does not include the drone class](https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/mmdet/datasets/coco.py#L21). Have you written your custom dataset class for mmdetection or have you added that class to original coco dataset file?

Secondly, what is the [input size](https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/configs/_base_/datasets/coco_detection.py#L8) you have been using in your experiments?

Would you mind sharing your dataset config files so that it is easier for us to replicate the results?

**Comment by KostadinovShalon** [comment]
Hi,

The CocoDataset class is a subclass of [CustomDataset](https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/mmdet/datasets/custom.py#L17). As you can see [here](https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/mmdet/datasets/custom.py#L73), if you define a set of classes, it will override the default list of classes (although we used the models trained on the COCO Dataset as initialization). So no, in this case, we did not write a custom dataset class.

Regarding the input size for Faster RCNN, we used the default (1333, 800) as you point out (same with DETR, SSD: 512 x 512 and YOLOv3: 608 x 608).

**Comment by fcakyon** [comment]
Thanks a lot for clearing things up.
