### ISSUE TITLE
MAV-VID (Average Object Size)

### ISSUE THREAD

**Issue by alsheabi** [KostadinovShalon/UAVDetectionTrackingBenchmark#10]
regards to Average Object Size for the MAV-VID dataset it's 3.61% of image size, not 0.66%. please update it.

**Comment by KostadinovShalon** [comment]
After running again our [statistics script](https://github.com/KostadinovShalon/UAVDetectionTrackingBenchmark/blob/main/scripts/dataset_statistics.py), I can confirm that the reported 0.66% is incorrect, but my results are 3.28%. I have updated accordingly. Thanks!
