### ISSUE TITLE
the second challenge dataset

### ISSUE THREAD

**Issue by redwangwangwang** [KostadinovShalon/UAVDetectionTrackingBenchmark#13]
Thank you for your excellent work. Please tell me how to find the version of the ant-uav data set you are using. Currently, the official website only has the third challenge dataset.

**Comment by guyleaf** [comment]
Hi, I have encountered the same problem before.
To find the previous challenge, you could check out the commit of the official GitHub Page.

For example: [2nd challenge](https://github.com/Anti-UAV/Anti-UAV.github.io/blob/a8783e5661e43644dda4dbaaecd29e52ad15ef39/dataset/index.html)
Search the keyword `download`, and you will find it.

As for the version of the dataset used in this benchmark, I think the author uses the [1st challenge](https://github.com/Anti-UAV/Anti-UAV.github.io/blob/91e79997f88be6347cb71965f3f91929057115b1/dataset/index.html).
