### ISSUE TITLE
missing requirements.txt file

### ISSUE THREAD

**Issue by fcakyon** [KostadinovShalon/UAVDetectionTrackingBenchmark#2]
Hello,

Would you mind sharing at least the opencv/torch/mmdetection/mmtracking package versions, or provide a full package list as a requirements.txt for your environment?

**Comment by KostadinovShalon** [comment]
Certainly,

I have added the OpenCV/Torch/MMDetection/MMTracking/MMCV versions to the README file under the [prerequisites section](https://github.com/KostadinovShalon/UAVDetectionTrackingBenchmark/blob/main/README.md#prerequisites). As we used the standard implementations of these frameworks for this work, we do not consider it necessary to add a requirements.txt file.

However, I attach the packages of the Conda environment used for this project. 
[reqs.txt](https://github.com/KostadinovShalon/UAVDetectionTrackingBenchmark/files/6319314/reqs.txt)

**Comment by fcakyon** [comment]
Thanks for the response!
