### ISSUE TITLE
MMTracking Modifications

### ISSUE THREAD

**Issue by fcakyon** [KostadinovShalon/UAVDetectionTrackingBenchmark#3]
Hello,

In your [paper](https://arxiv.org/pdf/2103.13933.pdf) you mention: `Marginal changes are required to the MMTracking toolbox to enable single stage detectors within Tracktor (as per 05/03/2021)`.

Are you going to open a PR to the original repo with your changes, or do you have any plans to release your edited version of mmtracking?

**Comment by KostadinovShalon** [comment]
@MattPoyser could you check on this?

**Comment by MattPoyser** [comment]
We can likely release the edited version of tracking after some further testing and improvements. Of course, the authors of mmtracking may release a more comprehensive framework imminently, so keep a look out on both.
