### ISSUE TITLE
Dataset heatmap/histogram plotting scripts

### ISSUE THREAD

**Issue by fcakyon** [KostadinovShalon/UAVDetectionTrackingBenchmark#4]
Do you have any intentions to share your dataset bbox location heatmap and area histogram scripts that you used in your [paper](https://arxiv.org/pdf/2103.13933.pdf)?

**Comment by KostadinovShalon** [comment]
I've added the scripts we used for dataset statistics (under the /scripts dir)

**Comment by fcakyon** [comment]
Thanks a lot!
