### ISSUE TITLE
MAV-VID dataset

### ISSUE THREAD

**Issue by liusiping10** [KostadinovShalon/UAVDetectionTrackingBenchmark#9]
Could you share the MAV-VID dataset with me? Thanks

**Comment by samils7** [comment]
I need this dataset too. Can someone share with us?

**Comment by KostadinovShalon** [comment]
Hi, I'm sorry for the late response, I'll share the MAV-VID dataset [here](https://durhamuniversity-my.sharepoint.com/:u:/g/personal/pfvn47_durham_ac_uk/Ea0QWh3MGbVGqwwzWM79iUoB9FL62ouUBhlo6C3789_Qzg?e=pBnSkO). This link will expire in one month.

**Comment by NewboySoCool** [comment]
Hi, in the MAV-VID, there is no labels, like [x, y ,w, h].

**Comment by sadiachow15** [comment]
Hi, is the mav vid dataset still available to donwload?

**Comment by KostadinovShalon** [comment]
Hi @sadiachow15 I think you can still download it with the [link I shared before](https://durhamuniversity-my.sharepoint.com/:u:/g/personal/pfvn47_durham_ac_uk/Ea0QWh3MGbVGqwwzWM79iUoB9FL62ouUBhlo6C3789_Qzg?e=pBnSkO), it actually never expired ;)

**Comment by shah5676** [comment]
HI, I can't find this dataset there. Would you help me find it?

**Comment by KostadinovShalon** [comment]
> HI, I can't find this dataset there. Would you help me find it?

I think the dataset has become private so I cannot share it anymore, sorry.

**Comment by KostadinovShalon** [comment]
> HI, I can't find this dataset there. Would you help me find it?

Hi there, after a second look, I realised you can still get access to the dataset via: https://github.com/alejodosr/adaptive-inattention
